name: spa_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  envify_generator: ^2.0.3
  build_runner: any
  envied_generator: ^0.3.0+3
dependencies:
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.7.1
  envied: ^0.3.0+3
  envify: ^2.0.3
  
  http: ^0.13.6
  mongo_dart: ^0.9.1
  path: ^1.8.3
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
